import { MaterialButton } from '../button/IconButtons'
import MaterialIcons from '@react-native-vector-icons/material-icons'
import { NouText } from '../NouText'
import { ServiceIcon } from '../service/Services'
import { resolveProfileUserAgent } from '@/lib/user-agents'
import { useContentJs } from '@/lib/hooks/useContentJs'
import { webRtcGuardScript$ } from '@/lib/webrtc'
import { composeDocumentStartScript, youTubeGuardScript$ } from '@/lib/youtube-guard';
import { getTimeSpoofScript } from '@/content/time'
import { parseJson } from '@/content/utils'
import { NavModalContent } from '../modal/NavModal'
import { useTabAnimation } from './tab-animation'
import { handleShortcuts } from '@/desktop/src/renderer/lib/shortcuts'
import { t } from 'i18next'
import { getProfileColor } from '@/lib/profile'
import { getProfileViewKey } from '@/lib/profile-view'